# Dzie≈Ñ piƒÖty DWthon üëã - Hack Outside the Box 

### Celem jest poznanie, czym jest tak zwany "aha moment"!

Czy wiesz co to jest "aha-moment"? To jest taki moment, kiedy m√≥wisz... "aha" üòÅ. Czyli co≈õ Ciƒô ol≈õni≈Ço i rzeczywisto≈õƒá (a przynajmniej jej kawa≈Çek) sta≈Ç siƒô bardziej dla Ciebie zrozumia≈Çy.

O "aha-momencie" mo≈ºna d≈Çugo m√≥wiƒá, lepiej podam Ci kilka przyk≈Çad√≥w.


### Facebook (7 przyjaci√≥≈Ç w 10 dni)
Je≈õli u≈ºytkownik dodaje co najmniej **10 znajomych** w ciƒÖgu **pierwszych 7 dni** od rejestracji, wtedy ten u≈ºytkownik bƒôdzie bardziej zaanga≈ºowany i na d≈Çu≈ºej zostanie w Facebook.

### Dropbox (1 plik, 1 folder, 1 urzƒÖdzenie)
Je≈õli u≈ºytkownik doda co najmniej jeden plik, jeden folder i zsynchronizuje siƒô z co najmniej jednym urzƒÖdzeniem, to wtedy ten u≈ºytkownik zostanie na d≈Çu≈ºej.

### LinkedIn - X po≈ÇƒÖcze≈Ñ w Y dni


To sƒÖ proste regu≈Çy, kt√≥re potrafiƒÖ opisaƒá najwa≈ºniejsze, co ma siƒô wydarzyƒá w firmie, aby firma ros≈Ça. Innymi s≈Çowy to jest stosowanie wprost regu≈Çy 80/20.


Trudno≈õƒá polega na tym, ≈ºe aby znale≈∫ƒá tƒô prostƒÖ regu≈Çƒô, to... no w≈Ça≈õnie, jak mo≈ºna jƒÖ znale≈∫ƒá? Przecie≈º takich prostych regu≈Ç mo≈ºe byƒá tysiƒÖce lub nawet miliony, zabraknie nam czasu, aby je wszystkie sprawdziƒá. Tutaj na pomoc nam mo≈ºe przyj≈õƒá `Machine Learning`.

### Gdzie zadawaƒá pytania ‚ùì 

Je≈õli napotkasz trudno≈õci podczas wykonywania zada≈Ñ z tego notebooka, to koniecznie napisz w kanale [dwthon_day5](https://bit.ly/3qEBEMv)

Pamiƒôtaj, aby szczeg√≥≈Çowo doprecyzowaƒá, z czym masz problem. Najlepiej wrzuƒá screen z kodem swoim lub b≈Çƒôdem, kt√≥ry widzisz i napisz, kt√≥rego zadania dotyczy :)

In [1]:
%%html
<iframe style="height:500px;width:100%" src="https://www.youtube.com/embed/EeFJLSS3_x0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

### Krok po kroku 

Nagra≈Çem dla Ciebie tak≈ºe materia≈Ç wideo "krok po kroku". W wideo poni≈ºej znajduje siƒô dok≈Çadnie to, co w tym notebooku tylko t≈Çumaczƒô wszystko, aby u≈Çatwiƒá Ci pracƒô i zrozumienie zagadnie≈Ñ i zada≈Ñ :) Obejrzyj, je≈õli potrzebujesz takiego dodatkowego wsparcia.

In [2]:
%%html
<iframe style="height:500px;width:100%" src="https://www.youtube.com/embed/7UTzlVkK17k" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

## Biblioteki
Potrzebujemy `pandas` i jeszcze trochƒô wiƒôcej innych bibliotek. 
* `DecisionTreeClassifier` - do trenowania modelu
* `sklearn.model_selection` walidacja modelu
* `gc` do sprzƒÖtania w pamiƒôci RAM

Dodatkowo u≈ºyjemy nowego bardziej zaawansowanego modelu `xgboost` oraz biblioteki `eli5` do podglƒÖdania wa≈ºno≈õci cech.
`from collections import Counter` przyda nam siƒô do wygodnego zliczenia liczby wystƒÖpie≈Ñ (np. ile razy klient kupi≈Ç produkt x).

In [3]:
import pandas as pd
import numpy as np

from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
import xgboost as xgb
import eli5 
from collections import Counter

import gc

## Wczytajmy dane

In [4]:
df = pd.read_hdf("../input/data.h5")

print(df.shape)
df.sample(5)

(820906, 9)

,order_id,customer_id,product_id,quantity,price_unit,price_total,country_id,order_date,is_canceled
471949,30256,700,711,10,635,6350,0,2010-02-16 14:49:00,False
486421,31368,1717,1312,4,675,2700,0,2010-03-03 16:49:00,False
842,55,39,495,5,165,825,0,2010-12-01 12:23:00,False
613183,40243,211,1506,12,145,1740,0,2010-07-09 10:26:00,False
33724,2441,1082,2372,12,125,1500,0,2011-01-11 15:13:00,False

## Przygotowujemy dane


To jest kod z poprzedniej lekcji. Jedynie pouk≈Çadamy kod w funkcji, aby ≈Çatwiej by≈Ço nam eksperymentowaƒá p√≥≈∫niej.

In [5]:
df_customers = (
    df[ ["price_total", "customer_id"] ]
    .groupby("customer_id")
    .agg("sum")
    .reset_index()
    .sort_values(by="price_total", ascending=False)
    .rename(columns={"price_total": "customer_price_total"})
)


df_customers["cumsum"] = df_customers["customer_price_total"].cumsum()
value_80prc = int(df["price_total"].sum() * 0.8)
df_customers["most_revenue_customer"] = df_customers["cumsum"] < value_80prc


top_customers = set(df_customers[ df_customers["most_revenue_customer"] ]["customer_id"].unique())

del df_customers
gc.collect()

def feature_engineering(df):
    df_customers = (
        df
        .groupby("customer_id")
        .agg(
            count_orders=("order_id", lambda x: len(set(x))),
            count_unq_products=("product_id", lambda x: len(set(x))),
            sum_quantity=("quantity", np.sum),
            sum_price_unit=("price_unit", np.sum),
            sum_price_total=("price_total", np.sum),
            count_unq_countries=("country_id", lambda x: len(set(x))),
            prob_canceled=("is_canceled", np.mean)
        ).reset_index()
    )
    
    
    
    return df_customers


def get_feats(df_customers, black_list=["most_revenue_customer"]):
    feats = list(df_customers.select_dtypes([np.number, bool]).columns)
    return [x for x in feats if x not in black_list]

def get_X_y(df_customers, top_customers, feats):
    df_customers["most_revenue_customer"] = df_customers["customer_id"].map(lambda x: x in top_customers)
    
    X = df_customers[feats].values
    y = df_customers["most_revenue_customer"].values
    
    return X, y


def train_and_get_scores(model, X, y, scoring="accuracy", cv=5):

    scores = cross_val_score(model, X, y, scoring=scoring, cv=cv)
    return np.mean(scores), np.std(scores)

## Model 1

‚òùÔ∏è Dok≈Çadnie to, co zrobili≈õmy ostatnio.

In [6]:
df_customers = feature_engineering(df)
feats = get_feats(df_customers)
X, y = get_X_y(df_customers, top_customers, feats)
model = DecisionTreeClassifier(max_depth=5)

train_and_get_scores(model, X, y)

(0.9996598639455783, 0.0004165798882284457)

Mamy wynik 99.9%.

Mo≈ºna siƒô cieszyƒá, ale... tak naprawdƒô opowiem Ci o jednym mechanizmie, kt√≥ry regularnie stosujƒô. Nazywam go wahad≈Ço.

Idea polega na tym, aby najpierw byƒá du≈ºym optymistƒÖ i bardzo upraszczaƒá rzeczywisto≈õƒá na poczƒÖtku. Nastƒôpnie, jak ju≈º mamy dobry wynik, to wchodzimy w "zupe≈Çnie inne buty". Wchodzimy w rolƒô aktywnego "krytyka", kt√≥ry pr√≥buje zrobiƒá wszystko, aby udowodniƒá, ≈ºe to, co zrobili≈õmy nie ma sensu. Powtarzamy tak w k√≥≈Çko. Robimy kilka iteracji :)  

Najwa≈ºniejsze jest to, ≈ºe dziƒôki prze≈ÇƒÖczaniu siƒô pomiƒôdzy rolami, mo≈ºna bardzo szybko biec od przodu, ale z drugiej strony mieƒá poczucie, ≈ºe to nadal ma sens!

## üß† W≈ÇƒÖczmy my≈õlenie krytycznie

Na ten moment wykonali≈õmy pierwszy krok, czyli optymistyczny i dostali≈õmy wynik 99%. Bardzo dobrze, ale... Problem polega na tym, ≈ºe `price_unit_total`jest zbyt mocnƒÖ cechƒÖ. Czyli ta cecha wprost m√≥wi, czy klient nale≈ºy do segmentu `top_customers` czy nie. Dlatego teraz musimy co najmniej tƒô cechƒô wy≈ÇƒÖczyƒá i sprawdziƒá, jak zachowa siƒô model.


Wystarczy dodaƒá `sum_price_total` do listy, kt√≥rƒÖ bƒôdziemy ignorowaƒá. 

Zobacz üëÄ.


## Model 2

In [7]:
df_customers = feature_engineering(df)
feats = get_feats(df_customers, black_list=["most_revenue_customer", "sum_price_total"])
X, y = get_X_y(df_customers, top_customers, feats)
model = DecisionTreeClassifier(max_depth=5)

train_and_get_scores(model, X, y)

(0.7722420031842525, 0.2652334198347648)

Jak widzisz, jako≈õƒá modelu nam spad≈Ça do 77%. Z jednej strony smutna sprawa üòÇ, ale z drugiej strony u≈ºywamy modelu ML, aby znajdowa≈Ç mniej oczywiste zale≈ºno≈õci. Bo te oczywiste cz≈Çowiek sam ≈Çatwo znajdzie sam ü§¶‚Äç‚ôÇÔ∏è.


### My≈õlenie optymistyczne
To teraz wr√≥ƒámy zn√≥w do bycia optymistƒÖ. Pamiƒôtasz na czym polega zasada wahad≈Ça? Wahamy siƒô tam i z powrotem ;) 


Mo≈ºna zmieniƒá model na bardziej zaawansowany i to powinno poprawiƒá wynik. U≈ºyjmy `xgboost`. Ta nazwa mo≈ºe Ci nic nie m√≥wiƒá i to jest ok na tym etapie üëå.

## Model 3

Zwr√≥ƒá uwagƒô, ≈ºe zmieni≈Ça siƒô ta linijka: `model = xgb.XGBClassifier(max_depth=5, n_estimators=50, learning_rate=0.3)`.

In [8]:
df_customers = feature_engineering(df)
feats = get_feats(df_customers, black_list=["most_revenue_customer", "sum_price_total"])
X, y = get_X_y(df_customers, top_customers, feats)
model = xgb.XGBClassifier(max_depth=5, n_estimators=50, learning_rate=0.3)

train_and_get_scores(model, X, y)

(0.8106769431176726, 0.08696513375768444)

## Mamy wynik 81%.

Spr√≥bujmy zrobiƒá pierwszƒÖ interpretacjƒô modelu i zobaczyƒá, co wg niego jest wa≈ºne.

In [9]:
model.fit(X, y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.3, max_delta_step=0, max_depth=5,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=50, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [10]:
eli5.show_weights(model, feature_names=feats)

### Wstƒôpnie wnioski:
#### TOP3 
- `sum_quantity` brzmi jako najwa≈ºniejsza cecha*
- `count_orders`
- `sum_price_unit`

Wyglada na to, ≈ºe cecha `count_unq_countries` jest ma≈Ço przydatna.


‚òùÔ∏è Trzeba uwa≈ºaƒá na to, co jest "wa≈ºne", bo do≈õwiadczenie pokazuje, ≈ºe to mo≈ºe byƒá do≈õƒá zmienne i w tej zmienno≈õci trzeba nauczyƒá siƒô poruszaƒá.


## Nastƒôpny krok

Mo≈ºemy teraz trochƒô pofilozofowaƒá nad tymi kilkoma cechami, ale to jest ma≈Ço istotne. Te cechy same w sobie sƒÖ do≈õƒá oczywiste. Nie ma poczucia "du≈ºej" warto≈õci dodanej. 

CiekawostkƒÖ okaza≈Ço siƒô, ≈ºe `sum_quantity` jest istotna. Tylko tutaj te≈º nie ma du≈ºego zaskoczenia.


Wygenerujmy zatem wiƒôcej cech, niech model znajdzie na co warto zwr√≥ciƒá naszƒÖ uwagƒô :) 


## Produkty


Mo≈ºemy dodaƒá dla ka≈ºdego produktu osobnƒÖ kolumnƒô i jako warto≈õƒá w tej kolumnie dodaƒá, ile produkt√≥w ju≈º by≈Ço kupionych (czyli suma). W ten spos√≥b chcemy znale≈∫ƒá, kt√≥re produkty sƒÖ "najciekawsze", warte tego, aby zwr√≥ciƒá na nie uwagƒô.

‚òùÔ∏è Oczywi≈õcie mo≈ºemy sprawdziƒá ka≈ºdy produkt manualnie, ale mamy ich ponad 3.8k, mo≈ºe to nam trochƒô zajƒÖƒá czasu. U≈ºyjmy lepiej do tego ML, bƒôdzie szybciej, sprawniej i efektywniej.

Tylko najpierw trzeba przygotowaƒá dane. Zmie≈Ñmy naszƒÖ funkcjƒô `feature_engineering`.

In [11]:
def feature_engineering(df):
    
    def counter(vals):
        cntr = Counter()
        cntr.update(vals)
        return cntr
    
    df_customers = (
        df
        .groupby("customer_id")
        .agg(
            count_orders=("order_id", lambda x: len(set(x))),
            count_unq_products=("product_id", lambda x: len(set(x))),
            count_by_products=("product_id", lambda x:  counter(x) ),
            sum_quantity=("quantity", np.sum),
            sum_price_unit=("price_unit", np.sum),
            sum_price_total=("price_total", np.sum),
            count_unq_countries=("country_id", lambda x: len(set(x))),
            prob_canceled=("is_canceled", np.mean)
        ).reset_index()
    )
    
    
    
    return df_customers


df_customers  = feature_engineering(df)
df_customers.head()

,customer_id,count_orders,count_unq_products,count_by_products,sum_quantity,sum_price_unit,sum_price_total,count_unq_countries,prob_canceled
0,0,159,93,"{0: 89, 1: 73, 2: 69, 3: 68, 4: 32, 5: 36, 6: ...",22976,895827,5746671,1,0.010966
1,1,40,184,"{8: 8, 9: 4, 10: 4, 11: 4, 12: 3, 13: 15, 14: ...",3514,205962,910113,1,0.097727
2,2,30,139,"{25: 9, 26: 7, 27: 7, 28: 3, 29: 4, 30: 10, 31...",8971,95500,1337464,1,0.009050
3,3,9,40,"{44: 7, 1781: 1, 1179: 1, 112: 1, 508: 3, 581:...",1108,18626,226381,1,0.000000
4,4,14,11,"{54: 14, 1496: 2, 2288: 1, 2315: 1, 3432: 1, 4...",390,20028,346978,1,0.307692

Jak widzisz pojawi≈Ça siƒô nowa kolumna `count_by_products`. W ≈õrodku jest s≈Çownik. Zobaczmy dok≈Çadniej üëÄ.

In [12]:
df_customers["count_by_products"]

0       {0: 89, 1: 73, 2: 69, 3: 68, 4: 32, 5: 36, 6: ...
1       {8: 8, 9: 4, 10: 4, 11: 4, 12: 3, 13: 15, 14: ...
2       {25: 9, 26: 7, 27: 7, 28: 3, 29: 4, 30: 10, 31...
3       {44: 7, 1781: 1, 1179: 1, 112: 1, 508: 3, 581:...
4       {54: 14, 1496: 2, 2288: 1, 2315: 1, 3432: 1, 4...
                              ...
5874    {1709: 1, 409: 1, 170: 1, 662: 1, 253: 1, 255:...
5875    {2368: 1, 300: 1, 1385: 1, 2412: 1, 2059: 1, 1...
5876    {1827: 1, 869: 1, 2157: 1, 335: 1, 1931: 1, 21...
5877    {1038: 1, 701: 2, 495: 1, 353: 1, 189: 1, 484:...
5878                                             {694: 2}
Name: count_by_products, Length: 5879, dtype: object

W praktyce to oznacza, ≈ºe  `customer_id=0` kupi≈Ç np. `product_id=0` - 89 razy, `product_id=1` - 73 razy, `product_id=3` - 68 razy itd.


Fajnie by≈Çoby nam wypakowaƒá s≈Çownik do osobnych kolumn, na szczƒô≈õcie da siƒô to zrobiƒá bardzo ≈Çatwo. ‚åõÔ∏è Tylko poczekaj chwilkƒô na wykonanie.

In [13]:
df_count_products = df_customers["count_by_products"].apply(pd.Series).fillna(-1)
df_count_products.columns = ["product_{}".format(x) for x in df_count_products.columns]

df_count_products.head(5)

,product_0,product_1,product_2,product_3,product_4,product_5,product_6,product_7,product_8,product_9,...,product_4216,product_4219,product_4220,product_4222,product_4226,product_4231,product_4236,product_4237,product_4238,product_4239
0,89.0,73.0,69.0,68.0,32.0,36.0,34.0,35.0,18.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
1,6.0,-1.0,1.0,-1.0,-1.0,-1.0,-1.0,-1.0,8.0,4.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
2,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
3,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
4,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0

Mamy teraz osobny `dataframe` z 3878 kolumnami. Ka≈ºda kolumna to jest `product_id`. Warto≈õƒá -1 oznacza brak informacji, czyli  klient nie kupowa≈Ç tego produktu, natomiast ka≈ºda inna liczba (wiƒôksza ni≈º 0) oznacza, ile razy ten produkt by≈Ç kupiony (to jest trochƒô optymistyczne zdanie, ale na razie mo≈ºemy przyjƒÖƒá, ≈ºe jest ok).

‚òùÔ∏è Zwr√≥ƒá uwagƒô, ≈ºe pojawi≈Ça siƒô linijka zmiany nazwy produktu. `df_count_products.columns = ["product_{}".format(x) for x in df_count_products.columns]` W tym miejscu robimy bardzo prostƒÖ rzeczy, zamiast samego ID, np. 0 czy 2, dodajemy przedrostek, aby kolumna nazywa≈Ça siƒô  `product_0` czy `product_2`. To nam przyda siƒô za chwilƒô.


### Nastƒôpny krok

Po≈ÇƒÖczmy `df_count_products` z `df_customers` i wytrenujmy model. Aby to po≈ÇƒÖczyƒá u≈ºyjemy konstrukcji `concat()`. Wynikiem bƒôdzie to, ≈ºe dokleimy to "z boku". Innymi s≈Çowy liczba wierszy zostanie taka sama, liczba kolumn powiƒôkszy siƒô o 3878 üò±. Model pewnie ucieszy siƒô, bƒôdzie mia≈Ç, co optymalizowaƒá.

≈ÅƒÖczymy!

In [14]:
df_customers = pd.concat([df_customers, df_count_products], axis=1)
df_customers.shape

(5879, 3887)

Tak jak spodziewali≈õmy siƒô, liczba wierszy zosta≈Ça taka sama - 5879 (bo liczba wierszy to sƒÖ klienci, nowych klient√≥w nie przyby≈Ço). Liczba kolumn wzros≈Ça nam do 3887. Mo≈ºesz o tym pomy≈õleƒá, ≈ºe teraz ka≈ºdy klient posiada 3887 cech, czyli charakterystyk.

## ü§ñ Czas na trenowanie modelu

Najpierw sprawd≈∫my, czy jako≈õƒá modelu siƒô nam poprawi≈Ça.

Uwaga! Model potrzebuje czasu na trenowanie, wiƒôc mo≈ºesz spokojnie przez chwilƒô odpoczƒÖƒá. Model wykonuje "prostƒÖ" i powtarzalnƒÖ pracƒô, natomiast po Twojej stronie jest my≈õlenie koncepcyjnie. Przyzwyczajaj siƒô, to jest przysz≈Ço≈õƒá, kt√≥ra ju≈º do nas przysz≈Ça :)

In [15]:
#df_customers = feature_engineering(df)
feats = get_feats(df_customers, black_list=["most_revenue_customer", "sum_price_total"])
X, y = get_X_y(df_customers, top_customers, feats)
model = xgb.XGBClassifier(max_depth=5, n_estimators=50, learning_rate=0.3)

train_and_get_scores(model, X, y)

(0.8474117817339701, 0.08924212099402075)

Jako≈õƒá modelu poprawi≈Ça siƒô, mamy ju≈º ~85%. 

Przypomnƒô, ≈ºe same drzewa decyzyjne da≈Çy nam 77%. XGBoost na podstawowych cechach da≈Ç nam 81% i teraz mamy 85%.

Mo≈ºe siƒô wydawaƒá, ≈ºe to s≈Çabo, bo mieli≈õmy 99,9%. Chcƒô taki wynik znowu! 

Byƒá mo≈ºe to jest przykra wiadomo≈õƒá, ale czƒôsto model "stopuje" siƒô w≈Ça≈õnie w okolicy 60-70% i potem trzeba naprawdƒô postaraƒá siƒô, aby wycisnƒÖƒá wiƒôcej. No chyba, ≈ºe u≈ºyjemy oczywistych zale≈ºno≈õci, ale to jest ma≈Ço ciekawe. Lepiej jednak pozwoliƒá modelowi znale≈∫ƒá co≈õ, co mo≈ºe zaskoczyƒá.

Wytrenujmy model teraz niezale≈ºnie, aby mo≈ºna by≈Ço zajrzeƒá i sprawdziƒá, co dla niego jest wa≈ºne.

In [16]:
model.fit(X, y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.3, max_delta_step=0, max_depth=5,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=50, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [17]:
eli5.show_weights(model, feature_names=feats, top=50)

No teraz ju≈º przynajmniej mamy na co popatrzeƒá :). Widaƒá, ≈ºe wa≈ºno≈õƒá produktu `product_545` oraz `product_99` jest ponad `count_orders`. Oczywi≈õcie, tak jak m√≥wi≈Çem, tutaj trzeba ostro≈ºnie wyciƒÖgaƒá wnioski. Natomiast to, co jest jednoznaczne to to, ≈ºe `product_id=545` zas≈Çu≈ºy≈Ç na to, aby zwr√≥ciƒá na niego uwagƒô ü•≥. To sprawd≈∫my :).

In [18]:
customer_ids_by_product = set(df[ df["product_id"] == 545 ]["customer_id"].unique())
len(customer_ids_by_product )

168

Ten produkt kupi≈Ço nie tak wielu klient√≥w, tylko 168. Sprawd≈∫my, ilu z nich nale≈ºy do segmentu `most_revenue_customer`.

In [19]:

df_customers[ df_customers.customer_id.isin(customer_ids_by_product) ]["most_revenue_customer"].mean()

0.4166666666666667

No widzimy, ≈ºe mamy 42% klient√≥w, kt√≥rzy kupili co najmniej `product_id=545` i nale≈ºƒÖ do segmentu `most_revenue_customer`.

Przypomnƒô, ≈ºe normalnie mamy 22% klient√≥w, kt√≥rzy nale≈ºƒÖ do segmentu `most_revenue_customer`.

In [20]:
df_customers["most_revenue_customer"].mean()

0.225208368770199

Mo≈ºemy na szybko postawiƒá hipotezƒô (do zbadania) -  je≈õli klient kupi≈Ç `product_id=545` to prawdopodobie≈Ñstwo, ≈ºe bƒôdzie nale≈ºa≈Ç do segmentu `most_revenue_customer` prawie podwaja siƒô (od 23% do 42%). Brzmi jako "aha moment". Tƒô hipotezƒô warto jeszcze zbadaƒá dok≈Çadniej, ale je≈ºeli ona faktycznie dzia≈Ça, to oznacza, ≈ºe warto sprawiƒá, aby wiƒôcej ludzi kupowa≈Ço w≈Ça≈õnie `product_id=545`.

#### Sprawd≈∫my, ile kosztuje ten produkt. Mo≈ºe to jaki≈õ luksus ‚öúÔ∏è.

In [21]:
df[ df.product_id == 545 ]["price_unit"].value_counts()

125    126
39     103
42       5
246      3
106      1
Name: price_unit, dtype: int64

Z cenƒÖ tego produktu bywa r√≥≈ºnie, ale najczƒô≈õciej cena jednostkowa, to jedynie 1,25 lub 3,9 üò±. Taki ciekawy wniosek uda≈Ço siƒô znale≈∫ƒá w tak ≈Çatwy spos√≥b.

## Zadanie 5.1


Twoim zadaniem jest zrobiƒá podobnƒÖ analizƒô dla produktu.


### üí° Podpowiedzi: 

1. Przygotuj `df_products`
2. Dodaj wiƒôcej cech, przed dodali≈õmy `product_id`, ale mo≈ºesz zrobiƒá symetryczne lub wymy≈õl co≈õ innego (mo≈ºe `order_id`) lub jeszcze co≈õ innego, jest sporo pomys≈Ç√≥w :) 
3. Wytrenuj model. 
4. Zobacz, co dla modelu by≈Ço najbardziej istotne.

In [42]:
df_products = (
    df[ ["price_total", "product_id"] ]
    .groupby("product_id")
    .agg("sum")
    .reset_index()
    .sort_values(by="price_total", ascending=False)
    .rename(columns={"price_total": "product_price_total"})
)


df_products["cumsum"] = df_products["product_price_total"].cumsum()
value_80prc = int(df["price_total"].sum() * 0.8)
df_products["most_revenue_product"] = df_products["cumsum"] < value_80prc


top_products = set(df_products[ df_products["most_revenue_product"] ]["product_id"].unique())

del df_products
gc.collect()

def feature_engineering(df):
    
    def counter(vals):
        cntr = Counter()
        cntr.update(vals)
        return cntr
    
    df_products = (
        df
        .groupby("product_id")
        .agg(
            count_orders=("order_id", lambda x: len(set(x))),
            count_unq_customers=("customer_id", lambda x: len(set(x))),
            count_by_customers=("customer_id", lambda x:  counter(x) ),
            sum_quantity=("quantity", np.sum),
            sum_price_unit=("price_unit", np.sum),
            sum_price_total=("price_total", np.sum),
            count_unq_countries=("country_id", lambda x: len(set(x))),
            prob_canceled=("is_canceled", np.mean)
        ).reset_index()
    )
    
    
    
    return df_products


def get_feats(df_products, black_list=["most_revenue_product"]):
    feats = list(df_products.select_dtypes([np.number, bool]).columns)
    return [x for x in feats if x not in black_list]

def get_X_y(df_products, top_products, feats):
    df_products["most_revenue_product"] = df_products["product_id"].map(lambda x: x in top_products)
    
    X = df_products[feats].values
    y = df_products["most_revenue_product"].values
    
    return X, y


def train_and_get_scores(model, X, y, scoring="accuracy", cv=5):

    scores = cross_val_score(model, X, y, scoring=scoring, cv=cv)
    return np.mean(scores), np.std(scores)


df_products  = feature_engineering(df)
df_products.head()

,product_id,count_orders,count_unq_customers,count_by_customers,sum_quantity,sum_price_unit,sum_price_total,count_unq_countries,prob_canceled
0,0,5028,1494,"{0: 89, 15: 36, 19: 19, 23: 5, 43: 2, 46: 3, 6...",97329,1525206,26097687,22,0.025179
1,1,614,293,"{0: 73, 192: 4, 329: 4, 75: 6, 380: 3, 443: 2,...",4638,248166,1650981,6,0.028358
2,2,736,320,"{0: 69, 122: 2, 132: 10, 191: 2, 292: 8, 293: ...",7160,261086,2267898,11,0.016753
3,3,1475,706,"{0: 68, 15: 3, 28: 2, 34: 2, 40: 3, 42: 11, 68...",16707,742149,5850395,14,0.009699
4,4,601,324,"{0: 32, 22: 4, 64: 2, 75: 3, 89: 2, 106: 5, 11...",3804,552166,2979279,17,0.037994

In [43]:
df_products["count_by_customers"]

0       {0: 89, 15: 36, 19: 19, 23: 5, 43: 2, 46: 3, 6...
1       {0: 73, 192: 4, 329: 4, 75: 6, 380: 3, 443: 2,...
2       {0: 69, 122: 2, 132: 10, 191: 2, 292: 8, 293: ...
3       {0: 68, 15: 3, 28: 2, 34: 2, 40: 3, 42: 11, 68...
4       {0: 32, 22: 4, 64: 2, 75: 3, 89: 2, 106: 5, 11...
                              ...
3873                                            {4395: 1}
3874                      {327: 1, 580: 1, 150: 1, 47: 1}
3875                                       {47: 1, 68: 1}
3876                                             {448: 1}
3877                                             {398: 4}
Name: count_by_customers, Length: 3878, dtype: object

In [44]:
df_count_customers = df_products["count_by_customers"].apply(pd.Series).fillna(-1)
df_count_customers.columns = ["customer_{}".format(x) for x in df_count_customers.columns]

df_count_customers.head(5)

,customer_0,customer_1,customer_2,customer_3,customer_4,customer_5,customer_6,customer_7,customer_8,customer_9,...,customer_5869,customer_5870,customer_5871,customer_5872,customer_5873,customer_5874,customer_5875,customer_5876,customer_5877,customer_5878
0,89.0,6.0,-1.0,-1.0,-1.0,4.0,-1.0,-1.0,5.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0
1,73.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
2,69.0,1.0,-1.0,-1.0,-1.0,3.0,-1.0,-1.0,1.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
3,68.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0,3.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0
4,32.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,9.0,-1.0,...,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,-1.0,1.0,-1.0,-1.0

In [53]:
df_products = pd.concat([df_products, df_count_customers], axis=1)
df_products.shape

(3878, 5889)

In [48]:
df_products = feature_engineering(df)
feats = get_feats(df_products, black_list=["most_revenue_product", "sum_price_total"])
X, y = get_X_y(df_products, top_products, feats)
model = xgb.XGBClassifier(max_depth=5, n_estimators=50, learning_rate=0.3)

train_and_get_scores(model, X, y)

(0.8633205853009643, 0.07143733771897691)

In [49]:
model.fit(X, y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.3, max_delta_step=0, max_depth=5,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=50, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [50]:
eli5.show_weights(model, feature_names=feats)

### Wstƒôpnie wnioski:
#### TOP3 
- `count_orders` brzmi jako najbardziej istotna cecha
- `sum_price_unit`
- `sum_quantity`

Wyglada na to, ≈ºe cecha `count_unq_countries` jest ma≈Ço przydatna

In [56]:
# df_products = feature_engineering(df)
feats = get_feats(df_products, black_list=["most_revenue_product", "sum_price_total"])
X, y = get_X_y(df_products, top_products, feats)
model = xgb.XGBClassifier(max_depth=5, n_estimators=50, learning_rate=0.3)

train_and_get_scores(model, X, y)

(0.8749321582973062, 0.08523619775762692)

In [58]:
model.fit(X, y)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.3, max_delta_step=0, max_depth=5,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=50, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [59]:
eli5.show_weights(model, feature_names=feats, top = 50)

Sprawd≈∫my `customer_1911`

In [62]:
product_ids_by_customer = set(df[ df["customer_id"] == 1911 ]["product_id"].unique())
len(product_ids_by_customer )

256

Ten klient zakupi≈Ç 256 produkt√≥w. Sprawd≈∫my ile z tych produkt√≥w nale≈ºy do segmentu `most_revenue_product`

In [64]:
df_products[ df_products.product_id.isin(product_ids_by_customer) ]["most_revenue_product"].mean()

0.6484375

Niemal≈ºe 65% produkt√≥w zakupionych przez customer_1911 znajduje siƒô w segmencie `most_revenue_product`

In [65]:
df[ df.customer_id == 1911 ]["price_unit"].value_counts()

42      41
125     41
85      35
375     35
165     34
295     23
195     19
495     11
210     11
65       8
254      7
169      5
415      5
39       4
425      4
145      4
1695     4
325      3
83       3
19       3
595      3
850      2
208      2
894      2
55       2
465      2
249      2
14       1
36       1
12       1
21       1
8        1
6        1
795      1
289      1
675      1
1495     1
825      1
225      1
1250     1
4        1
Name: price_unit, dtype: int64

`Na podstawie powy≈ºszych danych mo≈ºna stwierdziƒá ≈ºe jest to bardzo zr√≥≈ºnicowany klient. SƒÖ produkty, kt√≥re zakupi≈Ç 41 razy, ale majƒÖce do≈õƒá niskƒÖ cenƒô oraz sƒÖ zakupione pojedyncze produkty, kt√≥re majƒÖ znacznie wy≈ºszƒÖ cenƒô ni≈º te, kt√≥re zosta≈Çy kupione najwiƒôkszƒÖ ilo≈õƒá razy. `

Jak **wykonasz** zadanie, nale≈ºy zrobiƒá:

1. Zrzut ekranu na kt√≥rym widaƒá rozwiƒÖzania, wtedy dostaniesz bonus :)
2. Wrzuciƒá rozwiƒÖzanie na slacku do pokoju **[#dwthon_day5_done](https://bit.ly/3teY3l8)**
3. Dostaƒá bonus za dobrƒÖ robotƒô üí™ i jutro bƒôdzie kolejna porcja.

*Uwaga! Je≈õli masz problem z jakim≈õ zadaniem, czego≈õ nie wiesz, to pamiƒôtaj, ≈ºe mo≈ºesz zadawaƒá pytania! Na tym polega nauka :) Pytania zwiƒÖzane z 2 dniem DWthon zadawaj w kanale [#dwthon_day5](https://bit.ly/3qEBEMv)*.

## üß† W≈ÇƒÖczmy my≈õlenie krytycznie


Ta ca≈Ça nasza analiza by≈Ça oparta na `price_total`, czyli przychodach. Co ze zwrotami? Byƒá mo≈ºe nastƒÖpi≈Ç czas nieco bardziej wej≈õƒá do kr√≥liczej nory?

Na co jeszcze warto zwr√≥ciƒá krytycznƒÖ uwagƒô?  Podpowiem, ≈ºe jeszcze jest sporo rzeczy ;)

## üòá W≈ÇƒÖczmy my≈õlenie kreatywne

Pomy≈õl, jak mo≈ºesz wykorzystaƒá tƒô wiedzƒô, kt√≥rƒÖ tutaj uda≈Ço Ci siƒô zdobyƒá?

Najlepiej, aby pad≈Çy przyk≈Çady z Twojego podw√≥rka. Je≈õli nie masz (ale pomy≈õl, bo to tylko mo≈ºe siƒô wydawaƒá, ≈ºe nie ma) to pomy≈õl o swoim otoczeniu.

Od razu powiem, ≈ºe nie chodzi tylko o e-commerce. To mo≈ºe byƒá dowolna bran≈ºa. Regu≈Ça 80/20 jest uniwersalna. To samo dotyczy "aha-moment√≥w".

## ü§ùüó£Ô∏è Pomy≈õl o kooperacji i komunikacji

#### ‚òùÔ∏è Podziel siƒô swoimi przemy≈õleniami na slacku **[#dwthon_day5_ideas](https://bit.ly/3qFcb5R)**. Je≈õli masz pomys≈Ç, ale nie masz kodu - popro≈õ na slacku o pomoc, aby kto≈õ pom√≥g≈Ç Ci napisaƒá kod. Natomiast je≈õli masz kod, to koniecznie podziel siƒô. Dziƒôki temu kto≈õ inny bƒôdzie w stanie ≈Çatwo powt√≥rzyƒá i podzieliƒá siƒô swoimi przemy≈õleniami. Dziƒôki temu ka≈ºdy zyskuje :).

In [ ]:
%%html
<iframe style="height:500px;width:100%" src="https://www.youtube.com/embed/qC2MZcjGfcM" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>

## üëáüëáüëá Tw√≥j Feedback i delta rozwoju üëáüëáüëá

Daj mi znaƒá koniecznie, co sprawi≈Ço Ci przyjemno≈õƒá, co trudno≈õƒá oraz czego uda≈Ço siƒô nauczyƒá w tej kr√≥tkiej [ankiecie](https://bit.ly/3rEnOLD). Pozwoli mi ona ulepszyƒá zadania, a Tobie lepiej trakowaƒá sw√≥j rozw√≥j: win-win üòá

In [ ]:
%%html

<div data-tf-widget="zUbU39eg" data-tf-iframe-props="title=Feedback after 5 day" data-tf-medium="snippet" style="width:100%;height:400px;"></div><script src="//embed.typeform.com/next/embed.js"></script>


## [DW Club](https://bit.ly/3rGtHtv) ‚ù§Ô∏è

I oczywi≈õcie to jest bardzo dobry moment, aby w≈Ça≈õnie teraz do≈ÇƒÖczyƒá siƒô >> **[DW Club](https://bit.ly/3rGtHtv)** << bo **zyskujesz wiele** za ma≈ÇƒÖ cenƒô üòé. Zobacz:
1. dostƒôp do tego DWthon przez ca≈Çy czas, dla Ciebie to oznacza, ≈ºe mo≈ºesz wr√≥ciƒá do tematu po jego zako≈Ñczeniu wtedy kiedy tylko chcesz
2. gotowe ≈õrodowisko, kt√≥re czeka 24/7 na Ciebie, dzia≈Çaj wtedy jak masz czas, nie musisz nic instalowaƒá oraz utrzymywaƒá przez ca≈Çy czas (biblioteki ca≈Çy czas zmieniajƒÖ siƒô)
3. gotowe rozwiƒÖzania (opr√≥cz DWthon, ju≈º tam sporo rzeczy zebra≈Ço siƒô - np. master class, dwgym itd), mo≈ºesz inspirowaƒá siƒô, i te≈º traktowaƒá to jako "≈õciƒÖgawka", kt√≥rƒÖ masz pod rƒôkƒÖ jak tylko go potrzebujesz
4. determinacjƒô do dzia≈Çania (razem zwykle jest ≈Çatwiej), trudniej bƒôdzie przek≈Çadaƒá na potem ;)
5. oszczƒôdzaj czasem razem z nami, tym bardziej jak go masz bardzo ma≈Ço, sporo informacji filtrujemy przez nasze do≈õwiadczenia
6. praktyczna wiedza z praktykujƒÖcym, uczƒô Ciƒô osoba, kt√≥ra ca≈Çy czas realizuje i wdra≈ºa prawdziwy projekty. Zrobisz du≈ºy postƒôp, po prostu obserwujƒÖc spos√≥b my≈õlenia i praktykujƒÖc
7. przyjazna spo≈Çeczno≈õƒá, czyli spokojnie mo≈ºesz pytaƒá, rozwa≈ºaƒá, dyskutowaƒá (bardzo dbamy o to, aby szacunek by≈Ç na wysokim poziomie)


Co najmniej jedne nowe zadanie miesiƒôcznie... I jeszcze wiele innych korzy≈õci dla Ciebie

### >> [Do≈ÇƒÖczasz siƒô teraz](https://bit.ly/3rGtHtv) <<?

## üí™ Pochwal siƒô ≈õwiatu, ≈ºe DWthon za TobƒÖ üí™ 

Uda≈Ço Ci siƒô! Jeste≈õ na mecie, koniecznie powiedz o tym innym. Byƒá mo≈ºe kogo≈õ to zmotywuje do dzia≈Çania, a dodatkowo warto m√≥wiƒá g≈Ço≈õno o nowych umiejƒôtno≈õciach i do≈õwiadczeniach, bo nigdy nie wiesz, jaka furtka mo≈ºe siƒô otworzyƒá ;) 

Pamiƒôtaj o dodaniu tag√≥w: `#dwclub` `#dwthon` `#hackoutsidethebox` `#machinelearning` `#datascience` ;) 


≈ömia≈Ço nas oznaczaj, bƒôdzie nam mi≈Ço :))

# üòá ≈öled≈∫ nas w social media

- [youtube](https://www.youtube.com/channel/UCRLds2lEuh7cfkvTR4I_ddQ)
- [facebook](https://www.facebook.com/groups/dataworkshop/)
- [linkedin](https://www.linkedin.com/company/dataworkshop)
- [instagram](https://www.instagram.com/data.vladimir/)
- [telegram](https://t.me/dataworkshop)


Te≈º ≈õmia≈Ço wysy≈Çaj zaproszenie na [LinkedIn Vladimira](https://www.linkedin.com/in/vladimiralekseichenko/). Tylko siƒô ucieszƒô z tego powodu ;)

## ü§ñ Polecam obejrzyƒá webinarium: [10 najpopularniejszych b≈Çƒôd√≥w w uczeniu maszynowym](https://bit.ly/3qKQbqg) ü§ñ